<?php

namespace Database\Seeders;

use App\Models\EmpleadoContrato;
use Illuminate\Database\Seeder;

class ContratoSeeder extends Seeder
{
    /**
     * Carga inicial de contratos (un vigente por empleado).
     * Requiere haber corrido PersonalSeeder primero.
     * Idempotente: actualiza por empleado_id.
     */
    public function run(): void
    {
        $contratos = [
            ['empleado_id' => 1, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '13', 'fecha_inicio' => '2025-12-16', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 2, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '17', 'fecha_inicio' => '2004-07-20', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 3, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '18', 'fecha_inicio' => '2016-08-01', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 4, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '19', 'fecha_inicio' => '1994-07-01', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 5, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '356', 'fecha_inicio' => '2002-08-15', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 6, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '359', 'fecha_inicio' => '1998-11-23', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 7, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '361', 'fecha_inicio' => '1997-01-19', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 8, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '362', 'fecha_inicio' => '1995-01-10', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 9, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '366', 'fecha_inicio' => '1990-01-01', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 10, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '369', 'fecha_inicio' => '2000-06-23', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 11, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '370', 'fecha_inicio' => '2000-06-24', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 12, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '372', 'fecha_inicio' => '1982-01-19', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 13, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '374', 'fecha_inicio' => '1977-06-20', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 14, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '376', 'fecha_inicio' => '1977-10-17', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 15, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '378', 'fecha_inicio' => '2000-06-30', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 16, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '379', 'fecha_inicio' => '1988-08-22', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 17, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '382', 'fecha_inicio' => '1987-08-31', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 18, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '384', 'fecha_inicio' => '1991-01-17', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 19, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '385', 'fecha_inicio' => '1991-01-07', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 20, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '386', 'fecha_inicio' => '1981-08-17', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 21, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '388', 'fecha_inicio' => '1981-03-23', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 22, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '389', 'fecha_inicio' => '1987-09-01', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 23, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '391', 'fecha_inicio' => '1989-03-20', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 24, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '393', 'fecha_inicio' => '1991-01-07', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 25, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '394', 'fecha_inicio' => '1994-01-17', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 26, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '395', 'fecha_inicio' => '1985-08-12', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 27, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '396', 'fecha_inicio' => '1995-09-01', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 28, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '397', 'fecha_inicio' => '1993-05-03', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 29, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '398', 'fecha_inicio' => '1989-11-20', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 30, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '399', 'fecha_inicio' => '1992-01-13', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 31, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '400', 'fecha_inicio' => '1989-01-23', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 32, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '401', 'fecha_inicio' => '1994-01-17', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 33, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '402', 'fecha_inicio' => '1985-06-17', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 34, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '403', 'fecha_inicio' => '1994-04-27', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 35, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '404', 'fecha_inicio' => '1990-03-12', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 36, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '406', 'fecha_inicio' => '1984-04-01', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 37, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '407', 'fecha_inicio' => '1990-10-08', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 38, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '408', 'fecha_inicio' => '1997-10-12', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 39, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '410', 'fecha_inicio' => '1978-06-26', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 40, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '413', 'fecha_inicio' => '1989-01-16', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 41, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '414', 'fecha_inicio' => '1988-07-25', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 42, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '418', 'fecha_inicio' => '1988-01-11', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 43, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '419', 'fecha_inicio' => '1993-08-16', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 44, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '426', 'fecha_inicio' => '1995-04-03', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 45, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '429', 'fecha_inicio' => '1990-06-05', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 46, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '430', 'fecha_inicio' => '1993-08-16', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 47, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '431', 'fecha_inicio' => '1994-02-02', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 48, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '432', 'fecha_inicio' => '1994-04-18', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 49, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '433', 'fecha_inicio' => '1995-02-01', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 50, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '434', 'fecha_inicio' => '1990-11-01', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 51, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '436', 'fecha_inicio' => '1994-04-18', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 52, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '437', 'fecha_inicio' => '1992-04-13', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 53, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '439', 'fecha_inicio' => '1990-03-19', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 54, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '440', 'fecha_inicio' => '1987-09-14', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 55, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '443', 'fecha_inicio' => '1989-02-01', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 56, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '444', 'fecha_inicio' => '1987-03-09', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 57, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '445', 'fecha_inicio' => '2002-11-01', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 58, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '446', 'fecha_inicio' => '1986-11-24', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 59, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '447', 'fecha_inicio' => '1998-09-04', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 60, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '448', 'fecha_inicio' => '1986-01-13', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 61, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '451', 'fecha_inicio' => '1997-03-03', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 62, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '453', 'fecha_inicio' => '1997-04-01', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 63, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '454', 'fecha_inicio' => '1980-09-14', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 64, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '460', 'fecha_inicio' => '2006-01-03', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 65, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '461', 'fecha_inicio' => '2006-01-03', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 66, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '462', 'fecha_inicio' => '2006-01-23', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 67, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '463', 'fecha_inicio' => '2006-02-06', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 68, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '464', 'fecha_inicio' => '2007-01-02', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 69, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '466', 'fecha_inicio' => '2007-01-16', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 70, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '468', 'fecha_inicio' => '2011-07-25', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 71, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '469', 'fecha_inicio' => '2006-04-01', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 72, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '470', 'fecha_inicio' => '2004-07-10', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 73, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '471', 'fecha_inicio' => '2008-02-01', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 74, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '472', 'fecha_inicio' => '2008-01-16', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 75, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '473', 'fecha_inicio' => '2008-06-02', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 76, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '475', 'fecha_inicio' => '2009-05-01', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 77, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '476', 'fecha_inicio' => '2006-09-05', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 78, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '478', 'fecha_inicio' => '2007-01-06', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 79, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '479', 'fecha_inicio' => '2009-09-17', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 80, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '480', 'fecha_inicio' => '2005-12-01', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 81, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '481', 'fecha_inicio' => '2009-09-17', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 82, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '482', 'fecha_inicio' => '2005-05-11', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 83, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '483', 'fecha_inicio' => '2006-03-24', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 84, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '484', 'fecha_inicio' => '2003-12-04', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 85, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '485', 'fecha_inicio' => '2009-09-17', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 86, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '486', 'fecha_inicio' => '2009-09-22', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 87, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '487', 'fecha_inicio' => '2009-10-05', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 88, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '488', 'fecha_inicio' => '2007-05-24', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 89, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '489', 'fecha_inicio' => '2008-01-14', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 90, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '491', 'fecha_inicio' => '2009-02-26', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 91, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '495', 'fecha_inicio' => '2013-10-01', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 92, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '496', 'fecha_inicio' => '2013-11-05', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 93, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '497', 'fecha_inicio' => '2013-11-05', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 94, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '498', 'fecha_inicio' => '2013-11-11', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 95, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '499', 'fecha_inicio' => '2009-01-20', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 96, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '500', 'fecha_inicio' => '2008-06-01', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 97, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '501', 'fecha_inicio' => '2009-01-20', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 98, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '502', 'fecha_inicio' => '2012-03-21', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 99, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '503', 'fecha_inicio' => '2009-05-12', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 100, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '504', 'fecha_inicio' => '2007-01-16', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 101, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '505', 'fecha_inicio' => '2007-06-19', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 102, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '506', 'fecha_inicio' => '2014-01-02', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 103, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '507', 'fecha_inicio' => '2007-03-05', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 104, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '508', 'fecha_inicio' => '2013-02-25', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 105, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '509', 'fecha_inicio' => '2013-02-25', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 106, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '510', 'fecha_inicio' => '2009-08-03', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 107, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '512', 'fecha_inicio' => '2014-06-02', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 108, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '515', 'fecha_inicio' => '2011-11-24', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 109, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '516', 'fecha_inicio' => '2014-12-01', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 110, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '517', 'fecha_inicio' => '2014-12-01', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 111, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '518', 'fecha_inicio' => '2014-12-02', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 112, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '519', 'fecha_inicio' => '2013-08-05', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 113, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '520', 'fecha_inicio' => '2008-10-24', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 114, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '521', 'fecha_inicio' => '2013-03-06', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 115, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '522', 'fecha_inicio' => '2012-07-26', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 116, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '523', 'fecha_inicio' => '2013-04-30', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 117, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '524', 'fecha_inicio' => '2014-12-02', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 118, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '525', 'fecha_inicio' => '2008-03-03', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 119, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '526', 'fecha_inicio' => '2012-04-11', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 120, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '527', 'fecha_inicio' => '2012-12-12', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 121, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '528', 'fecha_inicio' => '2012-11-28', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 122, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '529', 'fecha_inicio' => '2014-12-01', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 123, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '530', 'fecha_inicio' => '2014-06-16', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 124, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '531', 'fecha_inicio' => '2014-12-01', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 125, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '532', 'fecha_inicio' => '2012-01-24', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 126, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '533', 'fecha_inicio' => '2014-12-01', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 127, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '535', 'fecha_inicio' => '2016-01-04', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 128, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '536', 'fecha_inicio' => '2016-03-01', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 129, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '537', 'fecha_inicio' => '2016-04-01', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 130, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '538', 'fecha_inicio' => '2016-02-01', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 131, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '539', 'fecha_inicio' => '2016-08-02', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 132, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '540', 'fecha_inicio' => '2016-08-01', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 133, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '541', 'fecha_inicio' => '2017-02-20', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 134, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '542', 'fecha_inicio' => '2017-02-20', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 135, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '544', 'fecha_inicio' => '2019-01-07', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 136, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '549', 'fecha_inicio' => '2022-08-15', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 137, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '550', 'fecha_inicio' => '2019-09-02', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 138, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '551', 'fecha_inicio' => '2021-05-10', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 139, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '552', 'fecha_inicio' => '2018-02-08', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 140, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '553', 'fecha_inicio' => '2019-10-21', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 141, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '554', 'fecha_inicio' => '2017-06-01', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 142, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '555', 'fecha_inicio' => '2019-04-03', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 143, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '556', 'fecha_inicio' => '2019-10-21', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 144, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '557', 'fecha_inicio' => '2019-01-08', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 145, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '558', 'fecha_inicio' => '2019-10-21', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 146, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '559', 'fecha_inicio' => '2019-10-21', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 147, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '560', 'fecha_inicio' => '2019-10-21', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 148, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '561', 'fecha_inicio' => '2019-10-21', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 149, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '562', 'fecha_inicio' => '2019-10-21', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 150, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '563', 'fecha_inicio' => '2021-04-05', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 151, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '564', 'fecha_inicio' => '2021-05-10', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 152, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '566', 'fecha_inicio' => '2024-01-02', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 153, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '570', 'fecha_inicio' => '2022-08-22', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 154, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '571', 'fecha_inicio' => '2025-06-03', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 155, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '572', 'fecha_inicio' => '2025-06-03', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
            ['empleado_id' => 156, 'tipo' => 'Indefinido', 'numero_contrato' => null, 'nro_item' => '576', 'fecha_inicio' => '2025-05-12', 'fecha_fin' => null, 'estado' => 'Vigente', 'es_vigente' => true, 'resolucion' => null],
        ];

        foreach ($contratos as $data) {
            EmpleadoContrato::updateOrCreate(
                ['empleado_id' => $data['empleado_id'], 'es_vigente' => true],
                [
                    'tipo' => $data['tipo'],
                    'numero_contrato' => $data['numero_contrato'],
                    'nro_item' => $data['nro_item'],
                    'fecha_inicio' => $data['fecha_inicio'],
                    'fecha_fin' => $data['fecha_fin'],
                    'estado' => $data['estado'],
                    'es_vigente' => $data['es_vigente'],
                    'resolucion' => $data['resolucion'],
                ]
            );
        }
    }
}
