<?php

namespace Database\Seeders;

use App\Models\Empleado;
use Illuminate\Database\Seeder;

class PersonalSeeder extends Seeder
{
    /**
     * Carga inicial del personal (211 registros).
     * Idempotente: actualiza por carnet de identidad.
     */
    public function run(): void
    {
        $personal = [
            ['nombre_completo' => 'Wilfredo Ariel Salinas Torrez', 'carnet_identidad' => '1793794', 'telefono' => '76204144', 'correo_electronico' => 'wsalinas59@gmail.com'],
            ['nombre_completo' => 'Juan Alex Arequipa Checa', 'carnet_identidad' => '3558498', 'telefono' => '72875873', 'correo_electronico' => 'j.arequipa@gmail.com'],
            ['nombre_completo' => 'Ximena Meguina Estevez Lopez', 'carnet_identidad' => '4822090', 'telefono' => '78693851', 'correo_electronico' => 'ximenaestevezlopez@gmail.com'],
            ['nombre_completo' => 'Maria Virginia Mostajo Cossio', 'carnet_identidad' => '1085366', 'telefono' => '70338541', 'correo_electronico' => 'mostajovirginia4@gmail.com'],
            ['nombre_completo' => 'Alberto Gunnar Iglesias Tapia', 'carnet_identidad' => '4630881', 'telefono' => '69699968', 'correo_electronico' => 'iglesiasgunnar@gmail.com'],
            ['nombre_completo' => 'Rocio Ivana Echavarria Ibarra', 'carnet_identidad' => '1119890', 'telefono' => '76111469', 'correo_electronico' => 'rocio.echavarriai@gmail.com'],
            ['nombre_completo' => 'Filiberta Coronado Jacome', 'carnet_identidad' => '1083912', 'telefono' => '68640000', 'correo_electronico' => 'filibertacoronado1964@gmail.com'],
            ['nombre_completo' => 'Javier Berrios Mendez', 'carnet_identidad' => '1109106', 'telefono' => '63768558', 'correo_electronico' => 'javierberriosmendez030@gmail.com'],
            ['nombre_completo' => 'Ricardo Vilcaez Cuizara', 'carnet_identidad' => '2741023', 'telefono' => '71156373', 'correo_electronico' => 'vilcaezricardoc@gmail.com'],
            ['nombre_completo' => 'Rolando Nestor Velasquez Butron', 'carnet_identidad' => '2756164', 'telefono' => '73408356', 'correo_electronico' => null],
            ['nombre_completo' => 'Marco Antonio Saavedra Arandia', 'carnet_identidad' => '3593419', 'telefono' => '65360550', 'correo_electronico' => 'msaavedraa10@gmail.com'],
            ['nombre_completo' => 'Victor Flores Santillan', 'carnet_identidad' => '1147824', 'telefono' => '73432607', 'correo_electronico' => 'vf9640294@gmail.com'],
            ['nombre_completo' => 'Hugo Mostacedo Rojas', 'carnet_identidad' => '1054552', 'telefono' => '72874857', 'correo_electronico' => 'h.mostacedo.77@gmail.com'],
            ['nombre_completo' => 'Wilfredo Arandia Dominguez', 'carnet_identidad' => '1053061', 'telefono' => '71165554', 'correo_electronico' => 'wilfredo.arandia.d@gmail.com'],
            ['nombre_completo' => 'Monica Patricia Civera Medina', 'carnet_identidad' => '1147092', 'telefono' => '79314795', 'correo_electronico' => 'mcivermedina@gmail.com'],
            ['nombre_completo' => 'Ronald Clemente Larrazabal Plaza', 'carnet_identidad' => '1093297', 'telefono' => '72871178', 'correo_electronico' => 'ronlp.23.rl@gmail.com'],
            ['nombre_completo' => 'Mario Lupe Garcia', 'carnet_identidad' => '1116190', 'telefono' => '72865474', 'correo_electronico' => 'mariolupegarcia@gmail.com'],
            ['nombre_completo' => 'Carlos Santillan Morales', 'carnet_identidad' => '1094549', 'telefono' => '72876309', 'correo_electronico' => 'carlos.sm1701@gmail.com'],
            ['nombre_completo' => 'Julian Romero Calderon', 'carnet_identidad' => '1100686', 'telefono' => '68661073', 'correo_electronico' => 'julianromerojrc@gmail.com'],
            ['nombre_completo' => 'Eulogio Cutipa', 'carnet_identidad' => '1083023', 'telefono' => '71162809', 'correo_electronico' => null],
            ['nombre_completo' => 'Anastacio Seno Melendres', 'carnet_identidad' => '1049406', 'telefono' => '74407598', 'correo_electronico' => 'anastacioseno@gmail.com'],
            ['nombre_completo' => 'Gonzalo Perez Peralta', 'carnet_identidad' => '1065161', 'telefono' => '76123267', 'correo_electronico' => 'gonzaloperez1020@gmail.com'],
            ['nombre_completo' => 'Desiderio Meneses Coronado', 'carnet_identidad' => '1093711', 'telefono' => '72874183', 'correo_electronico' => null],
            ['nombre_completo' => 'Ronal Portugal Cueto', 'carnet_identidad' => '1108563', 'telefono' => '71177535', 'correo_electronico' => 'portugalcuetor@gmail.com'],
            ['nombre_completo' => 'Victor Hugo Ramos Cruz', 'carnet_identidad' => '1107217', 'telefono' => '74402302', 'correo_electronico' => 'biktor5@gmail.com'],
            ['nombre_completo' => 'Octavio Bernal Ortiz', 'carnet_identidad' => '1107967', 'telefono' => '73441984', 'correo_electronico' => 'octaviobernal929@gmail.com'],
            ['nombre_completo' => 'Oscar Luis Nava Lopez', 'carnet_identidad' => '3627118', 'telefono' => '71153107', 'correo_electronico' => 'oronava1@gmail.com'],
            ['nombre_completo' => 'Segundino Cardozo Lazcano', 'carnet_identidad' => '1145002', 'telefono' => '72886085', 'correo_electronico' => 'segundinocar010794@gmail.com'],
            ['nombre_completo' => 'Victor Padilla Espindola', 'carnet_identidad' => '1067816', 'telefono' => '68646102', 'correo_electronico' => 'vpadillaespindola@gmail.com'],
            ['nombre_completo' => 'Juan Simon Baldiviezo Miranda', 'carnet_identidad' => '1074264', 'telefono' => '71164643', 'correo_electronico' => 'balduco.saimon@gmail.com'],
            ['nombre_completo' => 'Jorge Herrera Aramayo', 'carnet_identidad' => '1069667', 'telefono' => '68667472', 'correo_electronico' => 'jorgeherreraamarayo8@gmail.com'],
            ['nombre_completo' => 'Antony Martinez Huailla', 'carnet_identidad' => '1069673', 'telefono' => '72865247', 'correo_electronico' => 'amartinez@gmail.com.bo'],
            ['nombre_completo' => 'Serafin Paniagua Serrudo', 'carnet_identidad' => '7520291', 'telefono' => '74436400', 'correo_electronico' => null],
            ['nombre_completo' => 'Isaac Ramirez Trujillo', 'carnet_identidad' => '3719192', 'telefono' => '71174950', 'correo_electronico' => 'isaacra1972@gmail.com'],
            ['nombre_completo' => 'Manuel Flores', 'carnet_identidad' => '1076749', 'telefono' => '72864207', 'correo_electronico' => 'manuel72864@gmail.com'],
            ['nombre_completo' => 'Luis Choque Ortiz', 'carnet_identidad' => '1093771', 'telefono' => '72893368', 'correo_electronico' => 'luchito.camba.1@gmail.com'],
            ['nombre_completo' => 'Edgar Rolando Arancibia Cossio', 'carnet_identidad' => '1099496', 'telefono' => '63760596', 'correo_electronico' => 'arancibiarolando41@gmail.com'],
            ['nombre_completo' => 'Marco Antonio Porcel Torres', 'carnet_identidad' => '1082426', 'telefono' => '68627913', 'correo_electronico' => 'marcoporcel055@gmail.com'],
            ['nombre_completo' => 'Omar Vega Cardozo', 'carnet_identidad' => '1058032', 'telefono' => '72850337', 'correo_electronico' => 'omarvegacardozo@gmail.com'],
            ['nombre_completo' => 'Claudio Padilla Escalante', 'carnet_identidad' => '1396128', 'telefono' => '72885975', 'correo_electronico' => 'claudiopadillaescalante@gmail.com'],
            ['nombre_completo' => 'Rene Sanchez Santillan', 'carnet_identidad' => '1118749', 'telefono' => '72894431', 'correo_electronico' => 'sanchezsantillanrene@gmail.com'],
            ['nombre_completo' => 'Lino Zambrana Zarate', 'carnet_identidad' => '1099331', 'telefono' => '73476663', 'correo_electronico' => 'abog.laambrana@gmail.com'],
            ['nombre_completo' => 'Ivan Marcos Fortun Castellon', 'carnet_identidad' => '1085991', 'telefono' => '70312016', 'correo_electronico' => 'fortunivanmarcos@gmail.com'],
            ['nombre_completo' => 'Jaime Felix Cervantes Morodias', 'carnet_identidad' => '1107325', 'telefono' => '72884918', 'correo_electronico' => 'jaimuchus4@gmail.com'],
            ['nombre_completo' => 'Javier Ramiro Choque Macias', 'carnet_identidad' => '1109461', 'telefono' => '73426188', 'correo_electronico' => 'rame1122.jrcm@gmail.com'],
            ['nombre_completo' => 'Ramiro Wilfredo Torrez Zarate', 'carnet_identidad' => '1107026', 'telefono' => '67642716', 'correo_electronico' => 'torrezramiro004@gmail.com'],
            ['nombre_completo' => 'Claudio Ortiz Limachi', 'carnet_identidad' => '1113259', 'telefono' => '71176330', 'correo_electronico' => 'claudioortiz752@gmail.com'],
            ['nombre_completo' => 'Jorge Poquechoque Arcienega', 'carnet_identidad' => '1082406', 'telefono' => '72884578', 'correo_electronico' => 'jorgepoquechoquearcienega@gmail.com'],
            ['nombre_completo' => 'Franz Diaz Avila', 'carnet_identidad' => '1115276', 'telefono' => '73413207', 'correo_electronico' => 'franzdiazavila7@gmail.com'],
            ['nombre_completo' => 'Carlos Gonzalo Contreras Peñarrieta', 'carnet_identidad' => '1099497', 'telefono' => '70335810', 'correo_electronico' => 'carloscontrerasp0123@gmail.com'],
            ['nombre_completo' => 'Carlos Rafael Silva Olmos', 'carnet_identidad' => '1068176', 'telefono' => '68661045', 'correo_electronico' => 'csilvaolmos2019@gmail.com'],
            ['nombre_completo' => 'Juan Quiroz Vidal', 'carnet_identidad' => '3122283', 'telefono' => '72899701', 'correo_electronico' => null],
            ['nombre_completo' => 'Hilarion Agapito Zelaya Vargas', 'carnet_identidad' => '1111826', 'telefono' => '70324576', 'correo_electronico' => 'hilarionzelaya0@gmail.com'],
            ['nombre_completo' => 'Gonzalo Parraga Espinoza', 'carnet_identidad' => '1077207', 'telefono' => '72896653', 'correo_electronico' => 'papigon1307@gmail.com'],
            ['nombre_completo' => 'Freddy Flores Serrudo', 'carnet_identidad' => '1143609', 'telefono' => '73449485', 'correo_electronico' => null],
            ['nombre_completo' => 'Marcelo Chumacero Porcel', 'carnet_identidad' => '1076074', 'telefono' => '72885255', 'correo_electronico' => 'chumaceroporcelmarcelo@gmail.com'],
            ['nombre_completo' => 'Juan Ivan Aguilar Rodriguez', 'carnet_identidad' => '1085662', 'telefono' => '68799656', 'correo_electronico' => 'jiar4140@gmail.com'],
            ['nombre_completo' => 'Mirna Marlene Sandoval Araujo', 'carnet_identidad' => '1057185', 'telefono' => '72882246', 'correo_electronico' => 'mirnasandovalaraujo@gmail.com'],
            ['nombre_completo' => 'Delina Judith Velasquez Saravia', 'carnet_identidad' => '1061685', 'telefono' => '72852231', 'correo_electronico' => 'judivelsa23@gmail.com'],
            ['nombre_completo' => 'Ruben Daza Sandoval', 'carnet_identidad' => '1047375', 'telefono' => '71677907', 'correo_electronico' => 'dazasandovalruben@gmail.com'],
            ['nombre_completo' => 'Eloy Edgar Urquizu Herrera', 'carnet_identidad' => '1112437', 'telefono' => '72865306', 'correo_electronico' => 'eeurqui@gmail.com'],
            ['nombre_completo' => 'Ana Maria Perez Flores', 'carnet_identidad' => '1105054', 'telefono' => '71153715', 'correo_electronico' => 'amperezf18@gmail.com'],
            ['nombre_completo' => 'Daniel Duran Reyes', 'carnet_identidad' => '4117819', 'telefono' => '71174690', 'correo_electronico' => null],
            ['nombre_completo' => 'Carmen Rosa Miranda Gamboa', 'carnet_identidad' => '1112656', 'telefono' => '72897826', 'correo_electronico' => 'carmenrosamirandagamboa535@gmail.com'],
            ['nombre_completo' => 'Nestor Yucra Araoz', 'carnet_identidad' => '5492561', 'telefono' => '70312382', 'correo_electronico' => 'nyucra.a@gmail.com'],
            ['nombre_completo' => 'Maria Cruz Eliana Loredo Ayaviri', 'carnet_identidad' => '1090903', 'telefono' => '70320900', 'correo_electronico' => 'eliana.la00@gmail.com'],
            ['nombre_completo' => 'Ruth Mariel Dominguez Mendoza', 'carnet_identidad' => '1115697', 'telefono' => '67608107', 'correo_electronico' => 'dominguezruthmariel@gmail.com'],
            ['nombre_completo' => 'Vicente Juvenal Diaz Ramirez', 'carnet_identidad' => '4095666', 'telefono' => '73412456', 'correo_electronico' => 'diazjuvenal120@gmail.com'],
            ['nombre_completo' => 'Javier Gonzalo Garcia Barragan', 'carnet_identidad' => '1110250', 'telefono' => '72886042', 'correo_electronico' => 'javiergarcia@gmail.com'],
            ['nombre_completo' => 'Santos Villca Hurtado', 'carnet_identidad' => '5491004', 'telefono' => '77129415', 'correo_electronico' => 'villsanto14@gmail.com'],
            ['nombre_completo' => 'Meliton Ortiz Falon', 'carnet_identidad' => '3659980', 'telefono' => '72869438', 'correo_electronico' => 'melitonortizfalon@gmail.com'],
            ['nombre_completo' => 'Jose Ygnacio Calderon Cabrera', 'carnet_identidad' => '1141218', 'telefono' => '73422395', 'correo_electronico' => 'calderonygnacio0@gmail.com'],
            ['nombre_completo' => 'Jenny Canseco Abraham', 'carnet_identidad' => '1107569', 'telefono' => '72885085', 'correo_electronico' => 'jennycanseco2@gmail.com'],
            ['nombre_completo' => 'Olga Litzy Siles Rodas', 'carnet_identidad' => '3108949', 'telefono' => '72893552', 'correo_electronico' => 'olgasilesro@gmail.com'],
            ['nombre_completo' => 'Edwin Sandi Alba', 'carnet_identidad' => '1113154', 'telefono' => '74417170', 'correo_electronico' => 'esan.sandi@gmail.com'],
            ['nombre_completo' => 'Lucia Arcienega Duran', 'carnet_identidad' => '4634206', 'telefono' => '75449675', 'correo_electronico' => 'luciaarcienega0@gmail.com'],
            ['nombre_completo' => 'Heber Ramiro Villca Callapa', 'carnet_identidad' => '7472034', 'telefono' => '76116729', 'correo_electronico' => 'heberrvillca@gmail.com'],
            ['nombre_completo' => 'Mario Mendoza Castellon', 'carnet_identidad' => '1149231', 'telefono' => '67639473', 'correo_electronico' => null],
            ['nombre_completo' => 'Magaly Ordóñez Taboada', 'carnet_identidad' => '1115578', 'telefono' => '76117464', 'correo_electronico' => 'magalyord.tab@gmail.com'],
            ['nombre_completo' => 'Claudia Martha Fernandez Rojas', 'carnet_identidad' => '3652462', 'telefono' => '72893397', 'correo_electronico' => 'claufernavarro@gmail.com'],
            ['nombre_completo' => 'Eduardo Chambi Romero', 'carnet_identidad' => '5642364', 'telefono' => '72860356', 'correo_electronico' => 'eduardochambi45@gmail.com'],
            ['nombre_completo' => 'Ruperto Cardenas Montoya', 'carnet_identidad' => '3663046', 'telefono' => '76126464', 'correo_electronico' => 'ruper.cardenas10@gmail.com'],
            ['nombre_completo' => 'Mario Gonzales Sainz', 'carnet_identidad' => '1095696', 'telefono' => '72878640', 'correo_electronico' => 'gonzalessainzmario@hotmail.com'],
            ['nombre_completo' => 'Juan Mendez Sanchez', 'carnet_identidad' => '4082056', 'telefono' => '73472403', 'correo_electronico' => 'juanmendezsanchez86@gmail.com'],
            ['nombre_completo' => 'Ricardo Ninachi Vedia', 'carnet_identidad' => '5667881', 'telefono' => '75774426', 'correo_electronico' => null],
            ['nombre_completo' => 'Leslie Ronette Rojas Stevenson', 'carnet_identidad' => '3629844', 'telefono' => '70313852', 'correo_electronico' => 'leslierojass75@gmail.com'],
            ['nombre_completo' => 'Romaned Nayra Poppe Araujo', 'carnet_identidad' => '5667092', 'telefono' => '78689694', 'correo_electronico' => 'romitapa11@gmail.com'],
            ['nombre_completo' => 'Jaime Bernardino Condori Luna', 'carnet_identidad' => '4091703', 'telefono' => '73447892', 'correo_electronico' => 'jaimebcondori21@gmail.com'],
            ['nombre_completo' => 'Edwin Ruiter Miranda Moscoso', 'carnet_identidad' => '3656192', 'telefono' => '77120688', 'correo_electronico' => 'edwinruiterm@gmail.com'],
            ['nombre_completo' => 'Raul Soleto Cuellar', 'carnet_identidad' => '1087683', 'telefono' => '72851168', 'correo_electronico' => 'soletoandiadiego@gmail.com'],
            ['nombre_completo' => 'Romulo Bernal Garcia', 'carnet_identidad' => '1095464', 'telefono' => '75765048', 'correo_electronico' => 'romulobernalgarcia@gmail.com'],
            ['nombre_completo' => 'Ricarda Claudia Arze Martinez', 'carnet_identidad' => '4087506', 'telefono' => '75436006', 'correo_electronico' => 'ricardaclaudiaarzemartinez@gmail.com'],
            ['nombre_completo' => 'Maria Elena Villanueva Salazar', 'carnet_identidad' => '3629042', 'telefono' => '72873752', 'correo_electronico' => 'mvillanueva2175@gmail.com'],
            ['nombre_completo' => 'Marco Antonio Pacello Gorena', 'carnet_identidad' => '3653208', 'telefono' => '77134033', 'correo_electronico' => 'ma_pacello@hotmail.com'],
            ['nombre_completo' => 'Juan Carlos Vaca Guzman Arancibia', 'carnet_identidad' => '4096017', 'telefono' => '73444627', 'correo_electronico' => 'juancarlosvackjer@gmail.com'],
            ['nombre_completo' => 'Angel Ipiña Alcoba', 'carnet_identidad' => '5656360', 'telefono' => '73426447', 'correo_electronico' => 'ipinaalcoba26@gmail.com'],
            ['nombre_completo' => 'Reynaldo Cabrera Ballesteros', 'carnet_identidad' => '5644370', 'telefono' => '68630668', 'correo_electronico' => 'reynaldocabrera026@gmail.com'],
            ['nombre_completo' => 'Arnulfo Barriga Garcia', 'carnet_identidad' => '5686843', 'telefono' => '73464303', 'correo_electronico' => 'arnulfobarrigagarcia@gmail.com'],
            ['nombre_completo' => 'Juan Miranda Cayara', 'carnet_identidad' => '5633007', 'telefono' => '72873513', 'correo_electronico' => 'juanero.116@gmail.com'],
            ['nombre_completo' => 'Carlos Alvaro Navarro Soliz', 'carnet_identidad' => '5632297', 'telefono' => '67620360', 'correo_electronico' => 'carlosnavarrosoliz@gmail.com'],
            ['nombre_completo' => 'Heber Robert Garcia Arias', 'carnet_identidad' => '4068323', 'telefono' => '71163624', 'correo_electronico' => 'gheber428@gmail.com'],
            ['nombre_completo' => 'Raul Vargas Sanchez', 'carnet_identidad' => '5663906', 'telefono' => '72858362', 'correo_electronico' => 'vargasraul601@gmail.com'],
            ['nombre_completo' => 'Edmundo Rivera Padilla', 'carnet_identidad' => '5690674', 'telefono' => '70317347', 'correo_electronico' => 'redmundo348@gmail.com'],
            ['nombre_completo' => 'Samuel Ruiz Diaz', 'carnet_identidad' => '7467102', 'telefono' => '74450397', 'correo_electronico' => 'rsd.0.99.20.19860@gmail.com'],
            ['nombre_completo' => 'Edgar Mora Mora', 'carnet_identidad' => '7475020', 'telefono' => '72889338', 'correo_electronico' => 'moramoraedgar26@gmail.com'],
            ['nombre_completo' => 'Ronald Soliz Colque', 'carnet_identidad' => '5641877', 'telefono' => '74429173', 'correo_electronico' => 'ronaldsolizcolque3@gmail.com'],
            ['nombre_completo' => 'Juan Choque Santos', 'carnet_identidad' => '4037153', 'telefono' => '60935474', 'correo_electronico' => 'huwanshoke@gmail.com'],
            ['nombre_completo' => 'Juan Carlos Romero Cespedes', 'carnet_identidad' => '5634829', 'telefono' => '67645280', 'correo_electronico' => 'juanc.romeroc@gmail.com'],
            ['nombre_completo' => 'Alfaro Agustin Sanchez Gutierrez', 'carnet_identidad' => '3852189', 'telefono' => '72873869', 'correo_electronico' => null],
            ['nombre_completo' => 'Carmen Rosa Chumacero Linarez', 'carnet_identidad' => '1112833', 'telefono' => '69667040', 'correo_electronico' => 'carmen.shumi70@gmail.com'],
            ['nombre_completo' => 'Franklin Martinez Mancilla', 'carnet_identidad' => '5637491', 'telefono' => '72865325', 'correo_electronico' => 'martinezfranklin608@gmail.com'],
            ['nombre_completo' => 'Luis Marcelo Pablo Miranda Zelada', 'carnet_identidad' => '1053498', 'telefono' => '76127975', 'correo_electronico' => 'luismmz@hotmail.com'],
            ['nombre_completo' => 'Juan Carlos Rocha Caceres', 'carnet_identidad' => '4115241', 'telefono' => '73411795', 'correo_electronico' => 'tiochalo123@gmail.com'],
            ['nombre_completo' => 'Franklin Eliseo Avillo Mamani', 'carnet_identidad' => '6628855', 'telefono' => '73417418', 'correo_electronico' => 'frankavil22334@gmail.com'],
            ['nombre_completo' => 'Ronal Luna Caceres', 'carnet_identidad' => '5667813', 'telefono' => '63753069', 'correo_electronico' => 'lunacaceresronal@gmail.com'],
            ['nombre_completo' => 'Roberto Huaygua Mamani', 'carnet_identidad' => '4874168', 'telefono' => '67619507', 'correo_electronico' => 'robertohuaygua@gmail.com'],
            ['nombre_completo' => 'Juan Carlos Perez Calderon', 'carnet_identidad' => '4081283', 'telefono' => '74758473', 'correo_electronico' => 'juanwayra@gmail.com'],
            ['nombre_completo' => 'Wilson Jony Baspineiro Ferrufino', 'carnet_identidad' => '5665626', 'telefono' => '68665800', 'correo_electronico' => 'wilsonbaspineiro9@gmail.com'],
            ['nombre_completo' => 'Felix Aniceto Quenta Fajardo', 'carnet_identidad' => '7474544', 'telefono' => '73440950', 'correo_electronico' => 'felixquenta19872@gmail.com'],
            ['nombre_completo' => 'Efrain Carrasco Rodas', 'carnet_identidad' => '4083339', 'telefono' => '73124484', 'correo_electronico' => 'efraincarrascorodas@gmail.com'],
            ['nombre_completo' => 'Victor Zarate Estevez', 'carnet_identidad' => '5648893', 'telefono' => '74222265', 'correo_electronico' => 'victor.vzr55@gmail.com'],
            ['nombre_completo' => 'Noemi Jaldin Cossio', 'carnet_identidad' => '6431327', 'telefono' => '71163105', 'correo_electronico' => 'noemi.jaldin7@gmail.com'],
            ['nombre_completo' => 'Doris Soledad Revollo Flores', 'carnet_identidad' => '4080089', 'telefono' => '75446834', 'correo_electronico' => 'dorisrevollo4@gmail.com'],
            ['nombre_completo' => 'Trifon Marca Mansilla', 'carnet_identidad' => '1147127', 'telefono' => '73449877', 'correo_electronico' => 'marcatrifon741@gmail.com'],
            ['nombre_completo' => 'Jose Javier Quispe Ojeda', 'carnet_identidad' => '5642540', 'telefono' => '67645020', 'correo_electronico' => 'josejavierquispeojeda@gmail.com'],
            ['nombre_completo' => 'Edson Eliot Cabezas Barrientos', 'carnet_identidad' => '4094532', 'telefono' => '78688322', 'correo_electronico' => 'edcaba36@gmail.com'],
            ['nombre_completo' => 'Diego Casillas Espinoza', 'carnet_identidad' => '5669163', 'telefono' => '69685025', 'correo_electronico' => 'dcasillas730@gmail.com'],
            ['nombre_completo' => 'Beatriz Mendez Rodriguez', 'carnet_identidad' => '5666051', 'telefono' => '71156602', 'correo_electronico' => 'brodriguezmendez4@gmail.com'],
            ['nombre_completo' => 'Silvia Sanchez Avila', 'carnet_identidad' => '7556089', 'telefono' => '75795164', 'correo_electronico' => 'silvinasanchez1992@gmail.com'],
            ['nombre_completo' => 'Diego Arcienega Arancibia', 'carnet_identidad' => '3645866', 'telefono' => '76100750', 'correo_electronico' => 'darcienega@gmail.com'],
            ['nombre_completo' => 'Mirna Castro Inocentes', 'carnet_identidad' => '3656764', 'telefono' => '73443436', 'correo_electronico' => 'micai.cstro@gmail.com'],
            ['nombre_completo' => 'Weymar Wilfredo Coria Davalos', 'carnet_identidad' => '5493071', 'telefono' => '79300329', 'correo_electronico' => 'weymarcoria@gmail.com'],
            ['nombre_completo' => 'Cecilio Marcos Aizama Zenteno', 'carnet_identidad' => '5515488', 'telefono' => '72781553', 'correo_electronico' => 'marcos_aizama@hotmail.com'],
            ['nombre_completo' => 'Edgar Luis Uyuquipa Diaz', 'carnet_identidad' => '5632973', 'telefono' => '77113805', 'correo_electronico' => 'edgar.uyuquipa@gmail.com'],
            ['nombre_completo' => 'Franz Erwin Gabriel Fuentes', 'carnet_identidad' => '4036679', 'telefono' => '77479236', 'correo_electronico' => 'franzgidgabrielgid@gmail.com'],
            ['nombre_completo' => 'Sergio Lopez Chispas', 'carnet_identidad' => '5636450', 'telefono' => '75781012', 'correo_electronico' => 'sergiolopezchispas@gmail.com'],
            ['nombre_completo' => 'Veronica Forns Samso Benavides', 'carnet_identidad' => '7527007', 'telefono' => '69688982', 'correo_electronico' => 'veronicafsb1@gmail.com'],
            ['nombre_completo' => 'Carlos Reyes Liceras', 'carnet_identidad' => '4085155', 'telefono' => '73427096', 'correo_electronico' => 'carlosreyesliceras3@gmail.com'],
            ['nombre_completo' => 'Diego Mauricio Turdera Toledo', 'carnet_identidad' => '7487170', 'telefono' => '77134568', 'correo_electronico' => 'diego_turdera@hotmail.com'],
            ['nombre_completo' => 'Rene Paniagua Cabezas', 'carnet_identidad' => '5492422', 'telefono' => '72890334', 'correo_electronico' => 'paniaguarene507@gmail.com'],
            ['nombre_completo' => 'Edson Ademir Arandia Mostacedo', 'carnet_identidad' => '7501732', 'telefono' => '79310273', 'correo_electronico' => 'edson081191@gmail.com'],
            ['nombre_completo' => 'William Puma Ramos', 'carnet_identidad' => '6663431', 'telefono' => '75967141', 'correo_electronico' => 'pumawilliam2023@gmail.com'],
            ['nombre_completo' => 'Juani Cabero Melendres', 'carnet_identidad' => '7496119', 'telefono' => '68620165', 'correo_electronico' => 'caberomelendresjuani@gmail.com'],
            ['nombre_completo' => 'Nicolas Janko Mendez', 'carnet_identidad' => '7468456', 'telefono' => '72892201', 'correo_electronico' => '7468456n@gmail.com'],
            ['nombre_completo' => 'Israel Llanos Chicchi', 'carnet_identidad' => '7557007', 'telefono' => '67627632', 'correo_electronico' => 'israelllanos900@gmail.com'],
            ['nombre_completo' => 'Never Cabero Navarro', 'carnet_identidad' => '7514269', 'telefono' => '73436960', 'correo_electronico' => 'nevercitodylan49@gmail.com'],
            ['nombre_completo' => 'Jimer Cruz Segura', 'carnet_identidad' => '10349572', 'telefono' => '67653205', 'correo_electronico' => 'jhimer.cruzsegura@gmail.com'],
            ['nombre_completo' => 'Luis Miguel Duran Flores', 'carnet_identidad' => '10385686', 'telefono' => '67629517', 'correo_electronico' => 'luisduran509@gmail.com'],
            ['nombre_completo' => 'Luis Fernando Cardenas Ortuño', 'carnet_identidad' => '5834461', 'telefono' => '67862242', 'correo_electronico' => 'fernandocardenaso0123@gmail.com'],
            ['nombre_completo' => 'Rolando Olmos Rivas', 'carnet_identidad' => '8574689', 'telefono' => '60318146', 'correo_electronico' => 'roilo_rolo_16@hotmail.com'],
            ['nombre_completo' => 'Jeannette Calizaya Torres', 'carnet_identidad' => '5666773', 'telefono' => '71160544', 'correo_electronico' => 'jhanetcalizayatorres@gmail.com'],
            ['nombre_completo' => 'Marco Augusto Villalba Rojas', 'carnet_identidad' => '7468086', 'telefono' => '78689100', 'correo_electronico' => 'marcovr09@gmail.com'],
            ['nombre_completo' => 'Jhonatan Ortiz Balcera', 'carnet_identidad' => '12456257', 'telefono' => '76127798', 'correo_electronico' => 'jhonabalcera@gmail.com'],
            ['nombre_completo' => 'Lorents Isidoro Alanez Herrera', 'carnet_identidad' => '7298128', 'telefono' => '76144159', 'correo_electronico' => 'herrera.lorents@gmail.com'],
            ['nombre_completo' => 'Gustavo Campos Flores', 'carnet_identidad' => '10324890', 'telefono' => '70334494', 'correo_electronico' => 'gus_campos_flores456@hotmail.com'],
            ['nombre_completo' => 'Silvia Llave Rodriguez', 'carnet_identidad' => '4116628', 'telefono' => '67969049', 'correo_electronico' => 'llaverodriguezsilvia10@gmail.com'],
            ['nombre_completo' => 'Leandro Nelson Galvez Gonzales', 'carnet_identidad' => '1094499', 'telefono' => '74424258', 'correo_electronico' => 'nelsonleandro1234@gmail.com'],
            ['nombre_completo' => 'Pamela Flores Saavedra', 'carnet_identidad' => '6589671', 'telefono' => '67901002', 'correo_electronico' => 'pamelafloressaavedra6589671@gmail.com'],
            ['nombre_completo' => 'Milton Ivan Montellano Roldan', 'carnet_identidad' => '1104164', 'telefono' => '67625775', 'correo_electronico' => 'montellanoroldan@gmail.com'],
            ['nombre_completo' => 'Daniela Quispe Loayza', 'carnet_identidad' => '5698932', 'telefono' => '77422454', 'correo_electronico' => 'daniela0103ql@gmail.com'],
            ['nombre_completo' => 'Reyi Giovannotty Duran Pessoa', 'carnet_identidad' => '10324690', 'telefono' => '75448189', 'correo_electronico' => 'giovannottypessoa@gmail.com'],
            ['nombre_completo' => 'Alvaro Joaquin Navarro Cors', 'carnet_identidad' => '10381527', 'telefono' => '73432404', 'correo_electronico' => 'alvaro.navarrocors@gmail.com'],
            ['nombre_completo' => 'Miguel Rodrigo Mamani Carrasco', 'carnet_identidad' => '7480860', 'telefono' => '69696657', 'correo_electronico' => 'miguel.67.crj@gmail.com'],
            ['nombre_completo' => 'Dayler Olimbo Martinez', 'carnet_identidad' => '7576733', 'telefono' => '74426692', 'correo_electronico' => 'daylerolimbomartk@gmail.com'],
            ['nombre_completo' => 'Luis Fernando Alaka Cruz', 'carnet_identidad' => '7483039', 'telefono' => '61888288', 'correo_electronico' => 'lc9726966@gmail.com'],
            ['nombre_completo' => 'Jose Enrique Avendaño Cardozo', 'carnet_identidad' => '12740366', 'telefono' => '75789955', 'correo_electronico' => 'jo.enrique1996@gmail.com'],
            ['nombre_completo' => 'Aurelio Huanco Choque', 'carnet_identidad' => '11553860', 'telefono' => '72657173', 'correo_electronico' => 'huancocas@gmail.com'],
            ['nombre_completo' => 'Alfred Panozo Salazar', 'carnet_identidad' => '5668082', 'telefono' => '72893980', 'correo_electronico' => 'fuken32@gmail.com'],
            ['nombre_completo' => 'Eddy Rojas Paco', 'carnet_identidad' => '5489176', 'telefono' => '73468663', 'correo_electronico' => 'eddyrojas3011@gmail.com'],
            ['nombre_completo' => 'Javier Uyuquipa Colque', 'carnet_identidad' => '7524493', 'telefono' => '67624778', 'correo_electronico' => 'uyuquipajavier16@gmail.com'],
            ['nombre_completo' => 'Noel Villacorta Gonzales', 'carnet_identidad' => '12739273', 'telefono' => '63753723', 'correo_electronico' => 'noelvillacorta22@gmail.com'],
            ['nombre_completo' => 'Mario Avendaño Reyes', 'carnet_identidad' => '4119351', 'telefono' => '76121188', 'correo_electronico' => 'marioavendanoreyes05@gmail.com'],
            ['nombre_completo' => 'Yhonatan Anagua Huarachi', 'carnet_identidad' => '10385307', 'telefono' => '65264051', 'correo_electronico' => 'yhonatan12323@gmail.com'],
            ['nombre_completo' => 'Daniel Fernandez', 'carnet_identidad' => '10420058', 'telefono' => '67616462', 'correo_electronico' => 'danielf1210@gmail.com'],
            ['nombre_completo' => 'Erick Albert Palenque Mamani', 'carnet_identidad' => '7546323', 'telefono' => '61890203', 'correo_electronico' => 'palenqueerick54@gmail.com'],
            ['nombre_completo' => 'Alex Serrudo Orihuela', 'carnet_identidad' => '10376453', 'telefono' => '67608041', 'correo_electronico' => 'alexjhojanelc@gmail.com'],
            ['nombre_completo' => 'Ruhiter Castel Rocha', 'carnet_identidad' => '5630592', 'telefono' => '67615490', 'correo_electronico' => 'ruhiter_001@hotmail.com'],
            ['nombre_completo' => 'Braihan Calvimontes Cruz', 'carnet_identidad' => '7545802', 'telefono' => '72854183', 'correo_electronico' => 'braihancalvimontes@gmail.com'],
            ['nombre_completo' => 'Adriana Soliz Rojas', 'carnet_identidad' => '9429535', 'telefono' => '65706167', 'correo_electronico' => 'adrianasolizrojas03@gmail.com'],
            ['nombre_completo' => 'Mario Cardozo Montero', 'carnet_identidad' => '10364985', 'telefono' => '68762500', 'correo_electronico' => 'mariocardozoontero@gmail.com'],
            ['nombre_completo' => 'Jorge Fernando Poveda Ruiz', 'carnet_identidad' => '5646275', 'telefono' => '60304725', 'correo_electronico' => 'poveda.ruiz.2210@gmail.com'],
            ['nombre_completo' => 'Cesar Moreno Ayarachi', 'carnet_identidad' => '6590959', 'telefono' => '78732092', 'correo_electronico' => 'cemoreno33@gmail.com'],
            ['nombre_completo' => 'Armin Palacios Siles', 'carnet_identidad' => '7568642', 'telefono' => '76118811', 'correo_electronico' => 'arminpalaciossilesjr@gmail.com'],
            ['nombre_completo' => 'David Marcani Choque', 'carnet_identidad' => '10351094', 'telefono' => '73446598', 'correo_electronico' => 'marcanidavid93@gmail.com'],
            ['nombre_completo' => 'Porfirio Flores Ollisco', 'carnet_identidad' => '7568942', 'telefono' => '67654696', 'correo_electronico' => 'porfiflores3@gmail.com'],
            ['nombre_completo' => 'Micaela Espindola Núñez', 'carnet_identidad' => '10369997', 'telefono' => '69687316', 'correo_electronico' => 'micaelaespindola85@gmail.com'],
            ['nombre_completo' => 'Junior Josue Jimenez Duran', 'carnet_identidad' => '7198975', 'telefono' => '72890552', 'correo_electronico' => 'juniorj.jimenezduran@gmail.com'],
            ['nombre_completo' => 'Alfredo Mamani Quispe', 'carnet_identidad' => '6582122', 'telefono' => '73890200', 'correo_electronico' => 'alfredo.mamani0109@gmail.com'],
            ['nombre_completo' => 'Jaime Nina Montalvo', 'carnet_identidad' => '3410711', 'telefono' => '73356159', 'correo_electronico' => 'nina10jaime@gmail.com'],
            ['nombre_completo' => 'Delsi Mariela Figueroa Miranda', 'carnet_identidad' => '3657115', 'telefono' => '72560538', 'correo_electronico' => 'marielafm2022@gmail.com'],
            ['nombre_completo' => 'Marilin Fransis Quiroga Peducasse', 'carnet_identidad' => '12515673', 'telefono' => '73435581', 'correo_electronico' => 'fransis.quiroga.peducasse5@gmail.com'],
            ['nombre_completo' => 'Franz Ivan Sanchez', 'carnet_identidad' => '1148501', 'telefono' => '73410746', 'correo_electronico' => 'franzsanchezlp100@gmail.com'],
            ['nombre_completo' => 'Livan Rodolfo Alvarez Irala', 'carnet_identidad' => '6667551', 'telefono' => '72449703', 'correo_electronico' => 'libizero666@gmail.com'],
            ['nombre_completo' => 'Candelaria Tatiana Gonzales Ponce', 'carnet_identidad' => '1108777', 'telefono' => '72898661', 'correo_electronico' => 'gonzalesponcetatiana@gmail.com'],
            ['nombre_completo' => 'Angelica Leon Rios', 'carnet_identidad' => '5669856', 'telefono' => '68638515', 'correo_electronico' => 'riosangelica1129@gmail.com'],
            ['nombre_completo' => 'Osmana Carrasco Callejas', 'carnet_identidad' => '1090754', 'telefono' => '73400430', 'correo_electronico' => 'osmanacarrasco1@gmail.com'],
            ['nombre_completo' => 'Juana Leon Salazar', 'carnet_identidad' => '5699804', 'telefono' => '73445142', 'correo_electronico' => 'analeonsalazar123@gmail.com'],
            ['nombre_completo' => 'Jaime Eduardo Duran Mass', 'carnet_identidad' => '3260874', 'telefono' => '75781822', 'correo_electronico' => 'jamesmass007@hotmail.com'],
            ['nombre_completo' => 'Nestor Ramiro Carvajal Canizares', 'carnet_identidad' => '5658776', 'telefono' => '75789555', 'correo_electronico' => 'ramirocarvajal115@gmail.com'],
            ['nombre_completo' => 'Liset Gonzales Duran', 'carnet_identidad' => '7541466', 'telefono' => '74430693', 'correo_electronico' => 'gonzaleslisetduran@gmail.com'],
            ['nombre_completo' => 'Alis Nicol Delgadillo Arancibia', 'carnet_identidad' => '7513443', 'telefono' => '75450613', 'correo_electronico' => 'alisnicoldelgadilloa@gmail.com'],
            ['nombre_completo' => 'Carol Abigail Rios Nava', 'carnet_identidad' => '7879634', 'telefono' => '72858908', 'correo_electronico' => 'carol.rios220191@gmail.com'],
            ['nombre_completo' => 'Heynmi Andreitha Mendoza', 'carnet_identidad' => '5491119', 'telefono' => '71692603', 'correo_electronico' => 'mendozaandreita899@gmail.com'],
            ['nombre_completo' => 'Rodrigo Alejandro Gallardo Bejarano', 'carnet_identidad' => '5138887', 'telefono' => '70227734', 'correo_electronico' => 'gallardobejaranorodrigoa@gmail.com'],
            ['nombre_completo' => 'Edmundo Jesus Zilvetti Ferrufino', 'carnet_identidad' => '5496078', 'telefono' => '72870985', 'correo_electronico' => 'edmundozilveti@gmail.com'],
            ['nombre_completo' => 'Graciela Marquez Echalar', 'carnet_identidad' => '5643896', 'telefono' => '65265859', 'correo_electronico' => 'marquezgra.echalar@gmail.com'],
            ['nombre_completo' => 'Karla Andrea Reyes Torrez', 'carnet_identidad' => '3628093', 'telefono' => '73472011', 'correo_electronico' => 'kteyestorrez@gmail.com'],
            ['nombre_completo' => 'Lourdes Natalia Baldivieso Vargas', 'carnet_identidad' => '10387118', 'telefono' => '70318224', 'correo_electronico' => 'lunabaldivieso@outlook.com'],
            ['nombre_completo' => 'Edwin Santos Diaz', 'carnet_identidad' => '3657790', 'telefono' => '76121233', 'correo_electronico' => 'edwinsantosdiaz78@gmail.com'],
            ['nombre_completo' => 'Milton Avalos Daza', 'carnet_identidad' => '10383353', 'telefono' => '77132921', 'correo_electronico' => 'miltonavalosdaza01@gmail.com'],
            ['nombre_completo' => 'Jesus Valentin Tejerina Perez', 'carnet_identidad' => '7207052', 'telefono' => '69693667', 'correo_electronico' => 'tejerinaperezj@gmail.com'],
        ];

        foreach ($personal as $data) {
            Empleado::updateOrCreate(
                ['carnet_identidad' => $data['carnet_identidad']],
                [
                    'nombre_completo' => $data['nombre_completo'],
                    'telefono' => $data['telefono'],
                    'correo_electronico' => $data['correo_electronico'],
                    'estado' => true,
                ]
            );
        }
    }
}
